version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        env_file: .env   
        
    redis:
        image: redis
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
          - POSTGRES_USER=${DB_USER}
          - POSTGRES_HOSE=${DB_HOST}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=coins
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/10-schema.sql